"""cria tabela material

Revision ID: 3e2c4e1dcb36
Revises: 06cdf29d79e5
Create Date: 2026-07-03 09:45:26.601220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2c4e1dcb36'
down_revision: Union[str, Sequence[str], None] = '06cdf29d79e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('unidade_compra', sa.Enum('UN', 'FOLHA', 'PACOTE', 'ML', 'L', 'G', 'KG', 'CM', 'M', 'CM2', 'M2', 'CX', 'ROLO', name='unidademedida'), nullable=False),
    sa.Column('unidade_base', sa.Enum('UN', 'FOLHA', 'PACOTE', 'ML', 'L', 'G', 'KG', 'CM', 'M', 'CM2', 'M2', 'CX', 'ROLO', name='unidademedida'), nullable=False),
    sa.Column('fator_conversao', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valor_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('custo_unitario_base', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantidade_minima', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fator_conversao > 0', name='ck_material_fator_conversao_positivo'),
    sa.CheckConstraint('quantidade_atual >= 0', name='ck_material_quantidade_atual_nao_negativa'),
    sa.CheckConstraint('quantidade_minima >= 0', name='ck_material_quantidade_minima_nao_negativa'),
    sa.CheckConstraint('valor_compra >= 0', name='ck_material_valor_compra_nao_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_material_nome_ativo', 'material', ['nome'], unique=True, postgresql_where=sa.text('ativo = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_material_nome_ativo', table_name='material', postgresql_where=sa.text('ativo = true'))
    op.drop_table('material')
    # ### end Alembic commands ###
