"""cria tabela desperdicio

Revision ID: 6ff5a474f2c2
Revises: 9edda5f1b3cc
Create Date: 2026-07-03 10:04:31.597187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff5a474f2c2'
down_revision: Union[str, Sequence[str], None] = '9edda5f1b3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desperdicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_perdida', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('custo_perda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade_perdida > 0', name='ck_desperdicio_quantidade_positiva'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desperdicio')
    # ### end Alembic commands ###
