"""cria tabelas produto e produto_material

Revision ID: 943ca8040c0b
Revises: 3e2c4e1dcb36
Create Date: 2026-07-03 09:52:55.000606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943ca8040c0b'
down_revision: Union[str, Sequence[str], None] = '3e2c4e1dcb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco_venda >= 0', name='ck_produto_preco_venda_nao_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_produto_nome_ativo', 'produto', ['nome'], unique=True, postgresql_where=sa.text('ativo = true'))
    op.create_table('produto_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_utilizada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('quantidade_utilizada > 0', name='ck_produto_material_quantidade_positiva'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'material_id', name='uq_produto_material')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_material')
    op.drop_index('ix_produto_nome_ativo', table_name='produto', postgresql_where=sa.text('ativo = true'))
    op.drop_table('produto')
    # ### end Alembic commands ###
