"""cria tabelas producao e producao_item

Revision ID: 9edda5f1b3cc
Revises: 943ca8040c0b
Create Date: 2026-07-03 09:59:29.709207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edda5f1b3cc'
down_revision: Union[str, Sequence[str], None] = '943ca8040c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_produzida', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('data_producao', sa.Date(), nullable=False),
    sa.Column('custo_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lucro_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade_produzida > 0', name='ck_producao_quantidade_positiva'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producao_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_consumida', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('custo_unitario_snapshot', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('custo_total_item', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantidade_consumida > 0', name='ck_producao_item_quantidade_positiva'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['producao_id'], ['producao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producao_item')
    op.drop_table('producao')
    # ### end Alembic commands ###
